#!/bin/bash

### BEGIN INIT INFO
# Provides: firewall
# Required-Start: $local_fs $remote_fs $network $syslog
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start firewall.sh at boot time
# Description: Enable service provided by firewall.
### END INIT INFO

REDE_FUNCIONARIO="xxx.xxx.xxx.x/xx"
REDE_ALUNO="xxx.xxx.x.x/xx"

# Script de Firewall
### CORES
VERDE="\033[1;32m"
AMARELO="\033[1;33m"
AZUL="\033[1;34m"
VERMELHO="\033[1;31m"
END="\033[m"
###
ProgressBar() {
  tput civis
  for X in $(seq 20)
  do  
    for i in ..
    do  
      echo -en "\033[1D$i"
      sleep .1
    done
  done
  tput cnorm
}


case $1 in

stop)

	# Definindo Politica ACCEPT - ACEITA TUDO
	sudo iptables -t filter -P OUTPUT ACCEPT
	sudo iptables -t filter -P INPUT ACCEPT
	sudo iptables -t filter -P FORWARD ACCEPT

	# Limpar as Regras de todas as tableas
	sudo iptables -t filter -F
	sudo iptables -t nat -F
	sudo iptables -t mangle -F
	sudo iptables -t raw -F
	sudo iptables -t security -F

	# Bloquear a passagem de pacotes pelo kernel
	# echo 0 > /proc/sys/net/ipv4/ip_forward
	echo -en "Stopping Security Firewall ";ProgressBar; echo -e " [\033[0;32m ok\033[m ]"

;;


start)
	$0 stop
	sleep 0.5
	echo -en "Starting Security Firewall ";ProgressBar; echo -e " [\033[0;32m ok\033[m ]"
	
	# liberar a passagem de pacotes pelo kernel
	echo 1 > /proc/sys/net/ipv4/ip_forward
	
	# Liberar "MASCARAMENTO" de Pacotes da Rede Interna para a Internet
	sudo iptables -t nat -A POSTROUTING -s $REDE_FUNCIONARIO -d 0/0 -j MASQUERADE
	sudo iptables -t nat -A POSTROUTING -s $REDE_ALUNO -d 0/0 -j MASQUERADE

	# Politicas que bloqueiam qualquer tipo de Conexão
	sudo iptables -P OUTPUT DROP
	sudo iptables -P INPUT DROP
	sudo iptables -P FORWARD DROP

	# Iniciando as Regras
	bash /etc/rules
	bash /etc/rotas
	bash /etc/test-09052018
;;

restart)
	$0 start
;;

*)
	echo 'POR FAVOR USE "stop|start|restart"'
;;

esac
