#!/bin/bash

# PLACAS DE REDES
ETH_EMBRATEL=enp0s3
ETH_VIVO=enp0s8
GW_EMBRATEL=XXX.XXX.XXX.X
GW_VIVO=XXX.XXX.XX.X
LAN_FUNCIONARIOS=XX.XXX.XXX.X/XX
LAN_ALUNOS=XXX.XXX.X.X/XX

# vim /etc/iproute2/rt_tables
# ADD -> 
#250 IMBRATEL
#251 VIVO

# Adiciona a rota padrao ao link1
ip route flush cache # Limpa o cache de rotas
ip rule add fwmark 1 prio 20 table EMBRATEL # Pacotes com marcacao 1 vao para o IMBRATEL
ip rule add fwmark 2 prio 20 table VIVO # Pacotes com marcacao 2 vao para o VIVO
ip route add default via $GW_EMBRATEL dev $ETH_EMBRATEL table EMBRATEL # Associa a rota da IMBRATEL a interface de rede e tabela correspondentes
ip route add default via $GW_VIVO dev $ETH_VIVO table VIVO # Associa a rota da VIVO a interface de rede e tabela correspondentes
#ip route add default via $GW_LINK1

sudo iptables -t mangle -I PREROUTING -s $LAN_FUNCIONARIOS -j MARK --set-mark 1
sudo iptables -t mangle -I PREROUTING -s $LAN_ALUNOS -j MARK --set-mark 2

#ip route flush cache # Limpa o cache
#ip rule del fwmark 1 # Deleta as regras de acordo com as marcacoes
#ip rule del fwmark 2 # Deleta a rota padrao  
#ip route del default
