#!/bin/bash

# PLACAS DE REDES
LINK1=enp0s3
LINK2=enp0s8
GW_LINK1=10.0.2.2
GW_LINK2=192.168.15.1
LAN1=enp0s9
LAN2=enp0s10

#ip route flush cache # Limpa o cache
#ip rule del fwmark 2 # Deleta as regras de acordo com as marcacoes
#ip rule del fwmark 3 # Deleta a rota padrao  
#ip route del default

# Adiciona a rota padrao ao link1
ip route flush cache # Limpa o cache de rotas
ip rule add fwmark 1 prio 20 table IMBRATEL # Pacotes com marcacao 1 vao para o link1
ip rule add fwmark 2 prio 20 table VIVO # Pacotes com marcacao 2 vao para o link2
ip route add default via $GW_LINK1 dev $LINK1 table IMBRATEL # Associa a rota do link1 a interface de rede e tabela correspondentes
ip route add default via $GW_LINK2 dev $LINK2 table VIVO # Associa a rota do link1 a interface de rede e tabela correspondentes
#ip route add default via $GW_LINK1

iptables -t mangle -A PREROUTING -s 10.201.148.0/22 -o $LAN1 -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -s 192.168.0.0/22 -o $LAN2 -j MARK --set-mark 2
